<a href="https://colab.research.google.com/github/Kyle-t-Schmidt/pytorchRefresher/blob/main/tensorMathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math opeations

*   Add, subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand
*   Reassignment






In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
# multiplication
tensor_a * tensor_b


tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [15]:
# exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
# a different way of