<a href="https://colab.research.google.com/github/Kyle-t-Schmidt/pytorchRefresher/blob/main/tensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_toch3 = torch.arange(10)
my_toch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch4 = my_toch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Difference between reshape and view?

Both torch.reshape and torch.view are used to change the shape of a PyTorch tensor, but they have key differences in how they achieve this:
Similarities:
Both functions return a new tensor with the desired shape, sharing the same underlying data with the original tensor whenever possible.
Both functions can be used to reshape tensors efficiently, without copying data unnecessarily.
Differences:
1. Data Contiguity:
torch.view:
Requires the tensor to be contiguous in memory. If the tensor is not contiguous, torch.view will raise an error.
torch.reshape:
Works even if the tensor is not contiguous. If necessary, it will create a copy of the tensor to ensure contiguity before reshaping.
2. Memory Management:
torch.view:
Creates a new tensor that shares the same memory as the original tensor. Modifying the data in the new tensor will also change the data in the original tensor.
torch.reshape:
May create a copy of the tensor if the original tensor is not contiguous. In this case, modifying the data in the new tensor will not affect the original tensor.
3. Safety:
torch.view:
Offers better performance but is less safe because it requires contiguous tensors.
torch.reshape:
Is safer because it can work on non-contiguous tensors, but it may incur additional memory overhead if a copy is required.

**When to use each:**

torch.view:
Use this when you are certain the tensor is contiguous and you want to avoid unnecessary data copying for better performance.
torch.reshape:
Use this when you are unsure if the tensor is contiguous or if you need to reshape a non-contiguous tensor without worrying about the potential for data copying.