<a href="https://colab.research.google.com/github/Kyle-t-Schmidt/pytorchRefresher/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

*   A torch.tensor is a multidimensional matrix containing elements of a single data type
*   similar to np attays, but work better wityh GPUs
*   default data type is float32
*   more suitable for deep learning than np arrays





In [ ]:
import torch
import numpy as np

# Lists

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NP Arrays

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.20212777, 0.48730569, 0.36809793, 0.38358316],
       [0.27114804, 0.55888848, 0.7471465 , 0.91911758],
       [0.53872638, 0.39303959, 0.82545889, 0.26445067]])

# Tensors

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1568,  0.8951,  0.5860,  0.2037],
        [-0.1433, -2.0510, -0.3012, -1.3942],
        [-0.6472,  0.6806, -2.4145,  0.2203]])

In [ ]:
tensor_3d = torch.randn(2, 3,4)
tensor_3d

tensor([[[ 1.2243,  0.9950, -0.1595,  0.1105],
         [ 0.0258, -1.1357,  0.3682, -1.5266],
         [-0.4701, -0.3002,  0.5085,  0.2321]],

        [[ 0.8693, -0.5272,  0.2329,  1.0187],
         [-0.3033, -0.5483, -1.0370,  0.4272],
         [-0.1173, -1.4256, -0.6598, -0.1680]]])

In [ ]:
## create tensor from np array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2021, 0.4873, 0.3681, 0.3836],
        [0.2711, 0.5589, 0.7471, 0.9191],
        [0.5387, 0.3930, 0.8255, 0.2645]], dtype=torch.float64)